#!/bin/bash
git pull

git add .

datetime="$(date +'%r')"
date="$(date +'%m/%d/%Y')"

if [ "$1" != "" ]; then
	echo $1
    git commit -m "$1"
else
	echo "updated on $date at $datetime"
    git commit -m "updated on $date at $datetime"
fi

git push
