#!/bin/bash

rm -rf out
mkdir -p out
cd out
cp ../*.* ./
lualatex -shell-escape -interaction=nonstopmode -synctex=1 -file-line-error $1.tex
lualatex -shell-escape -interaction=nonstopmode -synctex=1 -file-line-error $1.tex
cp *.pdf ../
if [ "$2" == "-o" ]; then
	gio open ../$1.pdf
fi

