#!/bin/bash

/home/san/ProgramFiles/miktex/bin/lualatex -shell-escape -interaction=nonstopmode -synctex=1 -file-line-error "$1"
/home/san/ProgramFiles/miktex/bin/lualatex -shell-escape -interaction=nonstopmode -synctex=1 -file-line-error "$1"
rm *.aux
rm *.log
rm *.out
rm *.toc
rm latex.py
rm *.synctex.gz
rm *.py.out
rm *.py.err
if [ "$2" == "-o" ]; then
	gio open $(echo "$1" | cut -d'.' -f 1).pdf
fi