#!/bin/bash

nativefier https://calendar.google.com/calendar/u/0/r --tray --single-instance --user-agent "Mozilla/5.0 (Windows NT 10.0; rv:74.0) Gecko/20100101 Firefox/74.0" --inject nativefier_inject.js --widevine --name GoogleCalendar

