#!/bin/bash

if [ "$1" == "" ]; then
   echo "URL must be provided as first argument"
else
   if [ "$2" == "" ]; then
      echo "App name must be provided as second argument"
   else
      cd /home/$USER/ProgramFiles
      nativefier $1 --name $2 --tray --single-instance --user-agent "Mozilla/5.0 (Windows NT 10.0; rv:74.0) Gecko/20100101 Firefox/74.0" --inject nativefier_inject.js --widevine --internal-urls ".*"
   fi
fi



