#!/usr/bin/env Rscript

library(knitr)
library(reticulate)

args = commandArgs(trailingOnly=TRUE)

print(args)

use_python("/home/san/ProgramFiles/Anaconda/anaconda3/bin/python")

args = commandArgs(trailingOnly=TRUE)

opts_knit$set(out.format = "latex")
knit(args[1])