#!/usr/bin/env python

import re
import sys
import subprocess

def main(filename):
    with open(filename) as f:
        content = f.read()
    pckgs = re.findall(r'\\usepackage{.*}', content)
    
    for i in range(len(pckgs)):
        pckgs[i] = pckgs[i].replace('\\usepackage{', '').replace('}', '')

    for pckg in pckgs:
        subprocess.run(['tllocalmgr', 'install', pckg])


if __name__ == '__main__':
    main(sys.argv[1])
